### ISSUE TITLE
Set name of id field in genData

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#70] opened 2020-10-14 00:02 UTC
At the moment, `genData()` includes an argument `id` to specify the name of the id/index field in the data set being generated. This only works if no definition table created by `defData` is being used. This should be changed so that the argument works all the time. It would override any definition provided in the first `defData` statement.

**Comment by assignUser** [comment] 2020-10-14 09:04
Duplicate of #40 :D

**Closed by assignUser** 2020-10-14 09:04 UTC
Labels: feature
