### ISSUE TITLE
Unify genOrdCat & genCorOrdCat

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#34] opened 2020-09-11 18:59 UTC
~~Currently genOrdCat requires a variable to be specified in argument adjVar - there is no real reason this needs to be the case. If the value of adjVar is NULL, then the adjustment should be assumed to be 0 in all cases.~~

Merge genCorOrdCat into genOrdCat (with no correlation as default) allow creation 1 or many new cat vars. Deprecate genCorOrdCa (e.g. like [this](genCorOrdCa))

**Comment by assignUser** [comment] 2020-09-16 10:56
Hey @kgoldfeld I have some questions for this issue:
genCorOrdCat already supports this, in the doc it says: 
>Vector of adjustment variables name in dtName - determines logistic shift. This is specified assuming a cumulative logit link. The vector can be NULL, of length 1, or a length equal to the number of new categorical variables. 

Do I see correctly that genOrdCat can only add one var at a time so adjVar should be NULL or one var name? Is there a reason for the different behavior? Or should we adjust it to behave similar to genCorOrdCat?

**Comment by assignUser** [comment] 2020-09-16 11:37
Also what is the reason for the use of this check:
https://github.com/kgoldfeld/simstudy/blob/bfcecd68441e0105c0178cfea36aad47c00257d0/R/generate_data.R#L515
This also flags this call even though hit should work imho: `genOrdCat(genData(1),  baseprobs = probs, catVar = "grp")`.
If you want to make sure the passed argument is a data.table I would suggest:
``` r
library(data.table)
arg <- data.table()
is(arg, "data.table")
#> [1] TRUE
```

<sup>Created on 2020-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


In some other functions you also check arguments that do not have a default with `if(!missing(arg)) stop("")` afaik this is unnecessary as r will give you an error by itself if an argument without default is missing:
``` r
log()
#> Error in eval(expr, envir, enclos): argument "x" is missing, with no default
```

<sup>Created on 2020-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kgoldfeld** [comment] 2020-09-16 12:47
I definitely agree with your first point - I had never considered that option. So, checking that the passed argument is an existing data.table or will generate a data.table seems good.

As far as the second point, I guess I wanted to have my own customized message - but in this case I failed to actually include a message. But, I agree.

**Comment by kgoldfeld** [comment] 2020-09-16 12:52
Regarding genOrdCat - the adjVar should only be NULL or a single variable name. The reason genCorOrdCat can have multiple variable names is that the shift can be different for each of the outcomes generated (thought the outcomes will be correlated). But genOrdCat is generating only a single variable, so only one possible adjustment.

**Comment by assignUser** [comment] 2020-09-16 13:29
OK, I see the point of custom error messages, we can use https://github.com/tidyverse/glue and maybe https://github.com/r-lib/cli to make nice looking messages :).

I understand why adjVar should be length 1, my question was rather if we should allow for the creation of multiple cat vars in one go to have the same behavior as genCorOrdCat (sans the correlation obviously). Or do you think this would lower the readability ?

**Comment by kgoldfeld** [comment] 2020-09-16 13:47
What you are suggesting is there could be just a single function and the default correlation would be 0, and the user could specify any number of categorical variables, including just a single one. We could phase out genCorOrdCat and fuse it together with genOrdCat. This would give us a test case for deprecating.

**Comment by assignUser** [comment] 2020-09-16 14:03
I was not thinking about deprecating one but that sounds good, let's do it!

**Comment by kgoldfeld** [comment] 2020-09-16 14:04
I can't imagine it is heavily used function in any case - though who knows?

**Comment by assignUser** [comment] 2020-09-20 16:05
I think I have succesfully merged the two functions, I need to write some more test but manual testing looks promising. It is still in genOrdCat2 until i test it properly and make the changes to deprecate genCorOrdCat.

@kgoldfeld  please check out the latest change on the branch: https://github.com/kgoldfeld/simstudy/tree/assignUser/issue34
And let me know if it works as expected!

**Comment by kgoldfeld** [comment] 2020-09-21 17:15
I've starting checking out the function. My quick check with a single outcome looks OK. However, generating multiple columns doesn't seem to be quite right. It looks like the columns 2 through 5 are merely the same as column 1. Here's an example:

```r
library(simstudy)

baseprobs <- matrix(c(0.2, 0.1, 0.7,
                      0.7, 0.2, 0.1,
                      0.5, 0.2, 0.3,
                      0.4, 0.2, 0.4,
                      0.6, 0.2, 0.2), 
                    nrow = 5, byrow = TRUE)

# generate the data

seedno <- 1234
set.seed(seedno)                     
dT <- genData(10000)

dX <- genCorOrdCat(dT, adjVar = NULL, baseprobs = baseprobs, 
                   prefix = "q", rho = 0.15, corstr = "cs")

set.seed(seedno)                     
dT <- genData(10000)

dX1 <- simstudy:::genOrdCat2(dT, adjVar = NULL, baseprobs = baseprobs, 
                   prefix = "q", rho = 0.15, corstr = "cs")

dX[, table(q1)]
#> q1
#>    1    2    3 
#> 2017  972 7011
dX1[, table(q1)]
#> q1
#>    1    2    3 
#> 2017  972 7011

dX[, table(q2)]
#> q2
#>    1    2    3 
#> 7006 2046  948
dX1[, table(q2)]
#> q2
#>    1    2    3 
#> 2017  972 7011

dX[, table(q3)]
#> q3
#>    1    2    3 
#> 5046 2001 2953
dX1[, table(q3)]
#> q3
#>    1    2    3 
#> 2017  972 7011
```

**Comment by assignUser** [comment] 2020-09-21 23:26
The issue seems to be with turning the columns to factors. When we set `asFactor = FALSE` it works as intended:
``` r
library(simstudy)

baseprobs <- matrix(c(
  0.2, 0.1, 0.7,
  0.7, 0.2, 0.1,
  0.5, 0.2, 0.3,
  0.4, 0.2, 0.4,
  0.6, 0.2, 0.2
),
nrow = 5, byrow = TRUE
)

# generate the data

seedno <- 1234
set.seed(seedno)
dT <- genData(10000)

dX <- genCorOrdCat(dT,
  adjVar = NULL, baseprobs = baseprobs,
  prefix = "q", rho = 0.15, corstr = "cs"
)

set.seed(seedno)
dT <- genData(10000)

dX1 <- simstudy:::genOrdCat2(dT,
  adjVar = NULL, baseprobs = baseprobs,
  prefix = "q", rho = 0.15, corstr = "cs", asFactor = FALSE
)

dX[, table(q1)]
#> q1
#>    1    2    3 
#> 2017  972 7011
dX1[, table(q1)]
#> q1
#>    1    2    3 
#> 2017  972 7011
dX[, table(q2)]
#> q2
#>    1    2    3 
#> 7006 2046  948
dX1[, table(q2)]
#> q2
#>    1    2    3 
#> 7006 2046  948
dX[, table(q3)]
#> q3
#>    1    2    3 
#> 5046 2001 2953
dX1[, table(q3)]
#> q3
#>    1    2    3 
#> 5046 2001 2953
```

<sup>Created on 2020-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>


I will check it out.

**Comment by assignUser** [comment] 2020-09-22 00:02
Yeah it is caused by genFactor, specifically my assumption that it was vectorized already but it is just duplicating the same data under multiple rows. I will need to rework that to be able to use it as intended.

**Comment by assignUser** [comment] 2020-09-23 01:47
This should work properly now...

**Closed** 2020-09-24 13:55 UTC
Labels: docs, feature
